### ISSUE TITLE
Violates terms

### ISSUE THREAD

**Issue by jamen** [gabru-md/StarMe-Bro#1]
Hello @gabru-md, this actually violates GitHub's [Terms of Service § Account Terms](https://help.github.com/articles/github-terms-of-service/#b-account-terms) and [Acceptable Use](https://help.github.com/articles/github-terms-of-service/#c-acceptable-use)

If what you saw is an actual flaw, have you considered GitHub's [bug bounty program](https://bounty.github.com/)? I would suggest privatizing/deleting this repo, and taking it up there instead.

Keeping this repository public _before_ it is fixed, could disqualify you from money rewards, or potentially get you banned.

**Comment by gabru-md** [comment]
@jamen Thank You for letting me know that i could report it as a bug as well. I have deleted those files from my Repository and have written it to the bug bounty program of GITHUB.

I am sorry in any case ! This was just an attemp to use it for fun, But now i understand and have registered this issue.

Forgive me in any case :)
gabru-md
